name: FeedlyOpmlImportApplication

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_NAME: wdlhwzz
  GITHUB_EMAIL: hhxxttx74@gmail.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: execute application
        run: mvn -B clean compile exec:java -Dexec.mainClass="com.leeyom.opml.app.OpmlUtils" --file pom.xml
        env:
          GITHUB_NAME: ${{ env.GITHUB_NAME }}
          FEEDLY_TOKEN: ${{ secrets.FEEDLY_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          SC_KEY: ${{ secrets.SC_KEY }}

      - name: update README.md
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_TOKEN }}
          commit-message: ":memo: update feed.opml"
          files: README.md feed.opml
          rebase: 'true'
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}

      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "update OPML"
          files: |
            feed.opml
